version: '3.8'

services:
  # PostgreSQL with TimescaleDB
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: securewatch_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/01_init_schema.sql
      - ./infrastructure/database/correlation_schema.sql:/docker-entrypoint-initdb.d/02_correlation_schema.sql
    environment:
      POSTGRES_USER: securewatch
      POSTGRES_PASSWORD: securewatch
      POSTGRES_DB: securewatch
      TS_TUNE_MEMORY: "2GB"
      TS_TUNE_NUM_CPUS: "2"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U securewatch -d securewatch"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - securewatch_network

  # Redis Cluster
  redis:
    image: redis:7-alpine
    container_name: securewatch_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - securewatch_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka for log ingestion
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: securewatch_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - securewatch_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: securewatch_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - securewatch_network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Elasticsearch for log search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: securewatch_elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - securewatch_network

  # Kibana for visualization (optional)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: securewatch_kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - securewatch_network

  # Correlation Engine
  correlation-engine:
    build:
      context: ./apps/correlation-engine
      dockerfile: Dockerfile
    container_name: securewatch_correlation_engine
    environment:
      - NODE_ENV=development
      - PORT=4005
      - CORRELATION_ENGINE_PORT=4005
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=securewatch
      - DB_USER=securewatch
      - DB_PASSWORD=securewatch
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKER=kafka:29092
    ports:
      - "4005:4005"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - securewatch_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4005/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  securewatch_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data: