# Cargo configuration for SecureWatch Agent
# Optimizes build and test settings for cross-compilation and testing

[build]
# Use rustls by default for better cross-platform compatibility
rustflags = [
    # Enable additional security checks in debug builds
    "-C", "overflow-checks=on",
    # Improve stack traces in tests
    "-C", "force-frame-pointers=yes",
]

[env]
# Set environment variables for testing
RUST_BACKTRACE = "1"
RUST_LOG = "debug"

# Test-specific environment variables
SECUREWATCH_TEST_MODE = "true"
SECUREWATCH_LOG_LEVEL = "debug"

# Performance optimization for release builds
[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"

# Test-optimized profile
[profile.test]
opt-level = 1
debug = true
overflow-checks = true

# Benchmark profile
[profile.bench]
opt-level = 3
debug = false
overflow-checks = false
lto = "thin"

# Cross-compilation configuration for SecureWatch Agent

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.i686-pc-windows-gnu]
linker = "i686-w64-mingw32-gcc"

# GNU LLVM targets for Windows (better cross-compilation support)
[target.aarch64-pc-windows-gnullvm]
# ARM64 GNU LLVM target - uses LLVM linker with GNU ABI
linker = "rust-lld"
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-gnullvm]
# x86_64 GNU LLVM target
linker = "rust-lld"
rustflags = ["-C", "target-feature=+crt-static"]

# Legacy MSVC targets (kept for reference but recommend using GNU LLVM)
[target.aarch64-pc-windows-msvc]
# Uses default MSVC linker
linker = "rust-lld"

[target.arm64ec-pc-windows-msvc]
# ARM64EC (Emulation Compatible) target
linker = "rust-lld"

[target.x86_64-pc-windows-msvc]
# Uses default MSVC linker
linker = "rust-lld"

# Linux targets
[target.x86_64-unknown-linux-gnu]
# Uses default linker

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

# MUSL static targets
[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc"]

# macOS targets
[target.x86_64-apple-darwin]
# Uses default linker

[target.aarch64-apple-darwin]
# Uses default linker

# FreeBSD target
[target.x86_64-unknown-freebsd]
# Uses default linker